version: '3.7'

services:
    php:
        build: ./docker/php
        volumes: &php_volumes
            - ./app:/var/www/app:cached
            - ./logs/app:/var/www/app/var/log:cached
    nginx:
        build:
            context: ./docker/nginx
            args:
                DOCKER_ENV: "dev"
        ports:
            - "80:80"
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./app:/var/www/app:cached
    db:
        image: mariadb:10.4.8
        command: ["--default-authentication-plugin=mysql_native_password --max_allowed_packet=134217728 "]
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
